Main Web Application/Controllers/CollectionController.cs
using Main_Web_Application.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Main_Web_Application.Controllers
{
    [Authorize]
    public class CollectionController : Controller
    {
        public CollectablesDbContext Context { get; set; }

        public CollectionController()
        {
            Context = new CollectablesDbContext();
        }


        [HttpGet]
        [Route("~/Collection/List")]
        public ActionResult List(string sortBy = null, string searchString = null)
        {
            //Defining the list that will be returned
            List <CollectionObject> lstCollectionObjectsToReturn;

            //When the searcString parameter is not empty, return a matching object list by search string
            if (!String.IsNullOrWhiteSpace(Server.HtmlEncode(searchString)))
            {
                //Retrieve Collection Objects by search string
                lstCollectionObjectsToReturn = Context.CollectionObjects
                    .Where(x => x.Name.ToLower()
                    .Contains(searchString.ToLower()) || x.Description.ToLower().Contains(searchString.ToLower()))
                    .OrderByDescending(x => x.Id)
                    .ToList();

                return View("~/Views/Inventory/ListObjects.cshtml", lstCollectionObjectsToReturn);
            }

            //When the sort parameter is supplied, generate a list of objects that is sorted by the parameter value
            if (sortBy != null)
            {
                switch (sortBy.ToLower())
                {
                    case "name":
                        lstCollectionObjectsToReturn = Context.CollectionObjects.OrderBy(x => x.Name).ToList();
                        break;
                    case "hasbox":
                        lstCollectionObjectsToReturn = Context.CollectionObjects.OrderByDescending(x => x.HasBox).ToList();
                        break;
                    case "hasshipper":
                        lstCollectionObjectsToReturn = Context.CollectionObjects.OrderByDescending(x => x.HasShipper).ToList();
                        break;
                    case "condition":
                        lstCollectionObjectsToReturn = Context.CollectionObjects.OrderBy(x => x.Condition).ToList();
                        break;
                    case "manufacturer":
                        lstCollectionObjectsToReturn = Context.CollectionObjects.OrderBy(x => x.Manufacturer).ToList();
                        break;
                    case "genre":
                        lstCollectionObjectsToReturn = Context.CollectionObjects.OrderBy(x => x.Genre).ToList();
                        break;
                    case "type":
                        lstCollectionObjectsToReturn = Context.CollectionObjects.OrderBy(x => x.Type).ToList();
                        break;
                    case "value":
                        lstCollectionObjectsToReturn = Context.CollectionObjects.OrderByDescending(x => x.EstimatedValue).ToList();
                        break;
                    case "sold":
                        lstCollectionObjectsToReturn = Context.CollectionObjects.OrderByDescending(x => x.Sold).ToList();
                        break;
                    case "shipped":
                        lstCollectionObjectsToReturn = Context.CollectionObjects.OrderByDescending(x => x.DateShipped).ToList();
                        break;
                    default:
                        lstCollectionObjectsToReturn = Context.CollectionObjects.OrderByDescending(x => x.DateUpdated).ToList();
                        break;
                }

                return View("~/Views/Inventory/ListObjects.cshtml", lstCollectionObjectsToReturn);
            }
            else
            {
                //This is the default behavior - returns a list of objects sorted by the date on which the object was last updated, in descending order. 
                lstCollectionObjectsToReturn = Context.CollectionObjects.OrderByDescending(x => x.DateUpdated).ToList();

                return View("~/Views/Inventory/ListObjects.cshtml", lstCollectionObjectsToReturn);
            }
        }


        [HttpGet]
        [Route("~/Collection/View/{Id:int}")]
        public ActionResult View(int Id)
        {
            return View("~/Views/Inventory/ViewObject.cshtml", Context.CollectionObjects.Where(x => x.Id == Id).FirstOrDefault());
        }

        [HttpGet]
        [Route("~/Collection/Create")]
        public ActionResult Create()
        {
            return View("~/Views/Inventory/CreateObject.cshtml");
        }

        [HttpPost]
        [Route("~/Collection/Create")]
        public ActionResult Create(CollectionObject model)
        {

            if (ModelState.IsValid)
            {
                Context.CollectionObjects.Add(model);
                Context.SaveChanges();
                ModelState.Clear();
            }

            return View("~/Views/Inventory/CreateObject.cshtml");
        }

        [HttpGet]
        [Route("~/Collection/Edit/{id:int}")]
        public ActionResult Edit(int id)
        {
            return View("~/Views/Inventory/EditObject.cshtml", Context.CollectionObjects.Where(x => x.Id == id).FirstOrDefault());
        }

        [HttpPost]
        [Route("~/Collection/Edit/{id:int}")]
        public ActionResult Edit(CollectionObject model)
        {
            //If the model supplied is invalid, return the user back to the edit page
            if(!ModelState.IsValid)
            { 
                return View(model);
            }

            //using a new collection object, rather than the model object to avert overposting security vulnerability. 
            CollectionObject collectionObject = new CollectionObject();
            collectionObject = Context.CollectionObjects.Find(model.Id);
            collectionObject.HasBox = model.HasBox;
            collectionObject.Genre = model.Genre;
            collectionObject.Condition = model.Condition;
            collectionObject.Description = model.Description;
            collectionObject.HasShipper = model.HasShipper;
            collectionObject.Manufacturer = model.Manufacturer;
            collectionObject.Name = model.Name;
            collectionObject.Type = model.Type;
            collectionObject.Sold = model.Sold;
            collectionObject.EstimatedValue = model.EstimatedValue;
            collectionObject.SoldValue = model.SoldValue;
            collectionObject.BuyerName = model.BuyerName;
            collectionObject.BuyerAddress = model.BuyerAddress;
            collectionObject.DateShipped = model.DateShipped;
            collectionObject.BuyerComments = model.BuyerComments;

            if (User.IsInRole("Admin"))
            {
                collectionObject.CommissionPaid = model.CommissionPaid;
                collectionObject.CommissionDate = model.CommissionDate;
                collectionObject.CommissionComments = model.CommissionComments;
            }

            collectionObject.DateUpdated = DateTime.Now;
            Context.Entry(collectionObject).State = EntityState.Modified;
            Context.SaveChanges();

            ViewBag.EditSuccess = true;
            return View("~/Views/Inventory/EditObject.cshtml", Context.CollectionObjects.Where(x => x.Id == model.Id).FirstOrDefault());
        }

        [HttpPost]
        [Route("~/Collection/Edit/AddImage/{id:int}")]
        public ActionResult Edit_PostImage(int id, HttpPostedFileBase file)
        {
            try
            {
                if (file.ContentLength > 0 && (Path.GetExtension(file.FileName).ToLower() == ".jpg" || Path.GetExtension(file.FileName).ToLower() == ".jpeg" || Path.GetExtension(file.FileName).ToLower() == ".png"))
                {

                    using (var dbContextTransaction = Context.Database.BeginTransaction())
                    {

                        var colObject = Context.CollectionObjects.Where(x => x.Id == id).FirstOrDefault();
                        if (colObject == null)
                            throw new Exception("There is no such collection item to store the image for!");

                        var image = new CollectionObjectImage() { CollectionItem = colObject, DateAdded = DateTime.Now, ImageName = file.FileName };

                        colObject.DateUpdated = DateTime.Now;

                        colObject.Images.Add(image);
                        Context.SaveChanges();



                        string _FileName = Path.GetFileName(file.FileName);
                        string _path = Path.Combine(Server.MapPath("~/temp_images"), $"{image.Id}_{_FileName}");

                        //a check to determine if the file already exists before saving it into the directory
                        if (!System.IO.File.Exists(_path))
                        {
                            file.SaveAs(_path);
                        }
                        else
                            throw new Exception("A file already exists in this directory, cannot create a new file with the same name!");



                        var imageSecond = colObject.Images.Where(x => x.Id == image.Id).FirstOrDefault();

                        imageSecond.FullFilePath = _path;
                        imageSecond.ImageUrl = $"{image.Id}_{_FileName}";

                        Context.SaveChanges();


                        dbContextTransaction.Commit();
                    }

                    ViewBag.FileUploadsucceeded = true;
                }
                else
                {
                    ViewBag.FileUploadsucceeded = false;

                }

                return Redirect($"~/Collection/Edit/{id}");

            }
            catch
            {
                ViewBag.FileUploadsucceeded = false;

Main Web Application/Views/Inventory/CreateObject.cshtml
@model Main_Web_Application.Models.CollectionObject

@{
    ViewBag.Title = "Create New Collection Item";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create New Collection Item</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", autocomplete="OFF" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", autocomplete = "OFF" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HasBox, htmlAttributes: new { @class = "control-label col-md-2 cbControlLabel" })
        <div class="col-md-10">
            <div class="checkbox cbControlDiv">
                @Html.EditorFor(model => model.HasBox, new { htmlAttributes = new { @class = "checkbox ", } })
                @Html.ValidationMessageFor(model => model.HasBox, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HasShipper, htmlAttributes: new { @class = "control-label col-md-2 cbControlLabel" })
        <div class="col-md-10">
            <div class="checkbox cbControlDiv">
                @Html.EditorFor(model => model.HasShipper, new { htmlAttributes = new { @class = "checkbox ",  } })
                @Html.ValidationMessageFor(model => model.HasShipper, "", new { @class = "text-danger", })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Condition, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Condition, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Condition, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Manufacturer, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Manufacturer, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Manufacturer, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Genre, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Main Web Application/Views/Inventory/ListObjects.cshtml
@model IEnumerable<Main_Web_Application.Models.CollectionObject>
@using Main_Web_Application.Models
@{
    ViewBag.Title = "List Collection Items";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="padding-top:30px;"></div>
<h1 style="text-align:center;">Viewing Full Inventory</h1>
<div style="padding-bottom:30px;"></div>
<div class="row">
    <div class="col-md-4 col-md-offset-8">
        @{
            using (Html.BeginForm("List", "Collection", FormMethod.Get))
            {
                <input id="searchString" name="searchString" type="text" class="form-control" style="float:left;" />
                <input type="submit" class="btn btn-primary" style="float:left;" value="Search" />
            }
        }

    </div>
</div>
<div style="padding-bottom:10px;"></div>
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Name", "List", "Collection", new { sortBy = "name" }, null)
        </th>
        <th>
            @Html.ActionLink("Sold", "List", "Collection", new { sortBy = "sold" }, null)

        </th>
        <th>
            @Html.ActionLink("Shipped", "List", "Collection", new { sortBy = "shipped" }, null)
        </th>
        <th>
            @Html.ActionLink("Value", "List", "Collection", new { sortBy = "value" }, null)

        </th>
        <th>
            @Html.ActionLink("Box", "List", "Collection", new { sortBy = "hasbox" }, null)

        </th>
        <th>
            @Html.ActionLink("Shipper", "List", "Collection", new { sortBy = "hasshipper" }, null)

        </th>
        <th>
            @Html.ActionLink("Condition", "List", "Collection", new { sortBy = "condition" }, null)

        </th>
        <th>
            @Html.ActionLink("Manufacturer", "List", "Collection", new { sortBy = "manufacturer" }, null)

        </th>
        <th>
            @Html.ActionLink("Genre", "List", "Collection", new { sortBy = "genre" }, null)

        </th>
        <th>
            @Html.ActionLink("Type", "List", "Collection", new { sortBy = "type" }, null)

        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sold)
            </td>
            <td>
                @if (item.DateShipped != null)
                {
                    <input type="checkbox" class=" " checked disabled />
                }
                else
                {
                    <input type="checkbox" class=" " disabled />
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstimatedValue)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HasBox)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HasShipper)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Condition)
            </td>
            <td>
                @item.Manufacturer.GetDisplayName()
            </td>
            <td>
                @item.Genre.GetDisplayName()
            </td>
            <td>
                @item.Type.GetDisplayName()
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Collection", new { id = item.Id }, null)
            </td>
            <td>
                @Html.ActionLink("View", "View", "Collection", new { id = item.Id }, null)
            </td>
        </tr>
    }

</table>

Main Web Application/Views/Inventory/Report.cshtml
@model Main_Web_Application.Models.ReportObjectModel
@using System.Globalization
@{
    ViewBag.Title = "Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="margin-bottom:50px;"></div>
<div class="row">
    <div class="col-md-3">
        <fieldset>
            <legend>
                Value Breakdown
            </legend>
            <table class="table">
                <thead>
                    <tr>
                        <th>Total Estimated</th>
                        <th>Total Sold</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Model.TotalEstimatedValueOfCollection.ToString("C2", CultureInfo.CurrentCulture)</td>
                        <td>@Model.TotalSoldValueOfCollection.ToString("C2", CultureInfo.CurrentCulture)</td>
                    </tr>
                </tbody>
            </table>
        </fieldset>
        <fieldset>
            <legend>
                Misc Breakdown
            </legend>
            <table class="table">
                <thead>
                    <tr>
                        <th>Total Shipped</th>
                        <th>Need Shipping</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Model.TotalItemsShipped</td>
                        <td>@Model.CollectionItemsNeedShipping.Count</td>
                    </tr>
                </tbody>
            </table>
        </fieldset>
    </div>
    <div class="col-md-3">
        <fieldset>
            <legend>
                Sold Items Breakdown
            </legend>
            <table class="table">
                <thead>
                    <tr>
                        <th>Total Items</th>
                        <th>Items Sold</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Model.TotalCollectionItems</td>
                        <td>@Model.TotalSoldCollectionItems</td>
                    </tr>
                </tbody>
            </table>
        </fieldset>
    </div>
    <div class="col-md-3">
        <fieldset>
            <legend>
                Manufacturer Breakdown
            </legend>
            <table class="table">
                <thead>
                    <tr>
                        <th>Manufacturer Name</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ItemManufacturerBreakdown.Values.Distinct().ToArray())
                    {
                        <tr>
                            <td>@item.ToString()</td>
                            <td>@Model.ItemManufacturerBreakdown.Count(x => x.Value == item.ToString())</td>
                        </tr>
                    }
                </tbody>
            </table>
        </fieldset>
        <fieldset>
            <legend>
                Genre Breakdown
            </legend>
            <table class="table">
                <thead>
                    <tr>
                        <th>Genre</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model.ItemGenreBreakdown.Values.Distinct().ToArray())
                    {
                        <tr>
                            <td>@item.ToString()</td>
                            <td>@Model.ItemGenreBreakdown.Count(x => x.Value == item.ToString())</td>
                        </tr>
                    }
                </tbody>
            </table>
        </fieldset>
        <fieldset>
            <legend>
                Condition Breakdown
            </legend>
            <table class="table">
                <thead>
                    <tr>
                        <th>Condition</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ItemConditionBreakdown.Values.Distinct().ToArray())
                    {
                        <tr>
                            <td>@item.ToString()</td>
                            <td>@Model.ItemConditionBreakdown.Count(x => x.Value == item.ToString())</td>
                        </tr>
                    }
                </tbody>
            </table>
        </fieldset>
        <fieldset>
            <legend>
                Type Breakdown
            </legend>
            <table class="table">
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ItemTypeBreakdown.Values.Distinct().ToArray())
                    {
                        <tr>
                            <td>@item.ToString()</td>
                            <td>@Model.ItemTypeBreakdown.Count(x => x.Value == item.ToString())</td>
                        </tr>
                    }
                </tbody>
            </table>
        </fieldset>
    </div>
    <div class="col-md-3">
        <fieldset>
            <legend>
                Items Need Shipment
            </legend>
            <table class="table">
                <thead>
                    <tr>
                        <th>Item Name</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model.CollectionItemsNeedShipping)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@Html.ActionLink("View", "View", "Collection", new { Id = item.Id }, null)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </fieldset>
        <fieldset>
            <legend>
                Items Need Images
            </legend>
            <table class="table">
                <thead>
                    <tr>
                        <th>Item Name</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model.ItemsWithoutImages)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@Html.ActionLink("View", "View", "Collection", new { Id = item.Id }, null)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </fieldset>
    </div>
</div>

Main Web Application/Views/Inventory/ViewObject.cshtml
@model Main_Web_Application.Models.CollectionObject
@using Main_Web_Application.Models
@{
    ViewBag.Title = "View Collection Item Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View Collection Item Details</h2>

<div>
    <hr />

    <div class="row">
        <div class="col-md-8">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.DateCreated)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateCreated)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Sold)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Sold)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.EstimatedValue)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EstimatedValue)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.SoldValue)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SoldValue)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.HasBox)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.HasBox)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.HasShipper)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.HasShipper)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Condition)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Condition)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Manufacturer)
                </dt>

                <dd>
                    @Model.Manufacturer.GetDisplayName()
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Genre)
                </dt>

                <dd>
                    @Model.Genre.GetDisplayName()

                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Type)
                </dt>

                <dd>
                    @Model.Type.GetDisplayName()

                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.BuyerName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.BuyerName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.BuyerAddress)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.BuyerAddress)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateShipped)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateShipped)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.BuyerComments)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.BuyerComments)
                </dd>
            </dl>
                @if (User.IsInRole("Admin"))
                {
                <fieldset>
                    <legend>Commission Info</legend>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.CommissionPaid)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CommissionPaid)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.CommissionDate)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CommissionDate)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.CommissionComments)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CommissionComments)
                        </dd>
                    </dl>
                </fieldset>
                }
           

        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-12">
                    @if (ViewBag.FileUploadsucceeded != null && ViewBag.FileUploadsucceeded == true)
                    {
                        <label class="label-success">File Upload Succeeded!</label>
                    }
                    else if (ViewBag.FileUploadsucceeded != null && ViewBag.FileUploadsucceeded == false)
                    {
                        <label class="label-danger">File Upload Failed!</label>
                    }
                </div>
            </div>
            <div class="row">
                @foreach (var image in Model.Images)
                {
                    <div class="col-md-4" style="padding-bottom:15px;">
                        <a href="~/temp_images/@image.ImageUrl" target="_blank">
                            <img src="~/temp_images/@image.ImageUrl" style="width:100%;" />
                        </a>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <a href="~/Collection/List" class="btn btn-default">Back to Inventory</a>
        </div>
        <div class="col-md-2">
           @Html.ActionLink("Edit", "Edit", "Collection", new { id = Model.Id }, new { @class = "btn btn-primary"})
        </div>
    </div>
</div>

@section styles{

<style type="text/css">
    dt{
        padding-top:10px;
    }
    dd {
        padding-top: 10px;
    }
</style>    
    
}